### ISSUE TITLE
Track of events checklist

### ISSUE THREAD

**Issue by 2fd** [decentraland/places#95]
- [x] pages
- [x] filter change + place
- [x] favorite click + place
- [x] like/dislike
- [x] share
- [x] share fallback
- [x] jump-in + place
